name: Automating pull request

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    workflow_dispatch:

jobs:
  myj_ob:
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2
      - name: manual scripting
        run: echo Hello, world!

      
